#More than [players] players, plugin will start kick the player
players: 8
#PLayer must afk more than [max-idle-time] secs, and him will can get kick
max-idle-time: 3600
#The server must low than this value and plugin will start kick player
kick-tps: 18.50
#The message for kick player
kick-message: "&cYou have been AFK for too long and the server is under load."
#Kick afking player when server is full
kick-afking-players-when-server-is-full: true
#The message for kick player when full
kick-afking-full-message: "&cYou were kicked because the server is full and you are AFK."
